version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NPM_FLAGS: "--legacy-peer-deps"
    container_name: netzap
    restart: unless-stopped
    ports:
      - "3000:3000"
    # Required capabilities for zmap to work properly
    cap_add:
      - NET_RAW
      - NET_ADMIN
    networks:
      - netzap_network

networks:
  netzap_network:
    driver: bridge
